[tool.black]
line-length = 119
target-version = ['py312']

[tool.pytest.ini_options]
testpaths = [
    "tests",                              # Fast-LLM core tests
    "fast_llm_external_models/tests"      # External models tests
]
norecursedirs = ["Megatron-LM"]

[tool.isort]
profile = "black"
default_section = "THIRDPARTY"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 119
float_to_top = "True"
known_first_party = [
    "fast_llm",
]
